name: CI

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  # Test
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install poetry
      - name: Run tests
        run: |
          poetry install --no-interaction
          poetry run pytest tests/ --junitxml test-results/test.xml --cov src/pysymbolscanner --cov-report term-missing
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: test-results/**/*.xml